# Generated by Django 5.1.1 on 2024-10-04 20:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MinasPoint',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('departamen', models.CharField(verbose_name=80)),
                ('cod_dep', models.CharField(verbose_name=80)),
                ('municipio', models.CharField(verbose_name=80)),
                ('cod_mun', models.CharField(verbose_name=80)),
                ('zona', models.CharField(verbose_name=80)),
                ('vereda', models.CharField(verbose_name=80)),
                ('ano', models.CharField(verbose_name=80)),
                ('mes', models.CharField(verbose_name=80)),
                ('edad', models.CharField(verbose_name=80)),
                ('ocupacion', models.CharField(verbose_name=80)),
                ('genero', models.CharField(verbose_name=80)),
                ('condicion', models.CharField(verbose_name=80)),
                ('y', models.DecimalField(decimal_places=10, max_digits=20)),
                ('x', models.DecimalField(decimal_places=10, max_digits=20)),
                ('lugar_deto', models.CharField(verbose_name=80)),
                ('actividad', models.CharField(verbose_name=80)),
                ('y_cmt12', models.CharField(verbose_name=80)),
                ('x_cmt12', models.CharField(verbose_name=80)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
        ),
    ]
